### ISSUE TITLE
Unable to Save Kosinski Art

### ISSUE THREAD

**Issue by JoenickROS** [kirjavascript/Flex2#20] opened 2020-07-11 21:51 UTC
Flex gets stuck saving if you try to save kosinski art, and it also keeps you from saving any other files that were loaded with the object, even if the Kosinski file is cleared.

**Comment by kirjavascript** [comment] 2020-07-11 22:12
Tested this by trying to load level art and it works here so I cannot reproduce it.

Adding a debugger would be useful so I could tell what was going on

**Comment by kirjavascript** [comment] 2020-07-23 15:41
this is fixed now in version 0.0.7

**Closed by kirjavascript** 2020-07-23 15:41 UTC
