### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by SONIC123CDMANIA** [kirjavascript/Flex2#84] opened 2024-10-28 15:22 UTC
So, the OG Flex had a web version, but Flex 2 doesn't. Please make a web version.

**Comment by kirjavascript** [comment] 2024-10-28 18:16
The problem is that it needs access to the filesystem to support project files well

there is further discussion in this thread: https://github.com/kirjavascript/Flex2/issues/82

**Comment by SONIC123CDMANIA** [comment] 2024-10-28 18:31
Ah, ok.

**Comment by kirjavascript** [comment] 2024-11-28 22:53
closed in favour of the other thread

**Closed as completed by kirjavascript** 2024-11-28 22:53 UTC
